server:
  port: 9098
spring:
  application:
    name: masking-demo
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding.yml
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from t_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: wall
    props:
      sql.show: true

mybatis:
  type-aliases-package: com.yz.tfb.bean.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logback:
  dir: ./logs
  level: info
